In [ ]:
import numpy as np
from IPython.display import display as dp
#, Latex as lt

import sympy as sp
#sp.init_printing(use_latex=True)

In [ ]:
#เฉลยแบบฝึกหัดที่ 5.1.1
G = np.array([[56, 32], [28, 74]])

G_T = G.T
print("ทรานสโพสของ G คือ")
print(G_T)

ทรานสโพสของ G คือ
[[56 28]
 [32 74]]


In [ ]:
#เฉลยแบบฝึกหัดที่ 5.1.2
A = np.array([[23, 45], [67, 89]])
B = np.array([[34, 12], [56, 78]])
C = np.array([[10, 25], [30, 40]])

# คำนวณ (A + B) - C
result1 = (A + B) - C

# คูณ (A + B - C) กับ A
result2 = np.dot(result1, A)

print("(A + B) - C =\n")
print(result1)
print("\n((A + B) - C) * A =\n")
print(result2)

(A + B) - C =

[[ 47  32]
 [ 93 127]]

((A + B) - C) * A =

[[ 3225  4963]
 [10648 15488]]


In [ ]:
#เฉลยแบบฝึกหัดที่ 5.1.3
H = np.array([[17, 39], [50, 28]])
I = np.array([[64, 21], [12, 56]])

J = np.dot(H, I)
J_T = J.T

print("H * I =\n", J)
print("\nทรานสโพสของ H * I =\n", J_T)


H * I =
 [[1556 2541]
 [3536 2618]]

ทรานสโพสของ H * I =
 [[1556 3536]
 [2541 2618]]


In [ ]:
#เฉลยแบบฝึกหัดที่ 5.1.4
J = np.array([[21, 56], [13, 39]])
K = np.array([[14, 28], [17, 52]])

# หาทรานสโพสของ J และ K
J_T = J.T
K_T = K.T

# คูณทรานสโพส
L = np.dot(J_T, K_T)

print("\nทรานสโพสของ J =\n", J_T)
print("\nทรานสโพสของ K =\n", K_T)
print("\nทรานสโพส J * ทรานสโพส K =\n", L)


ทรานสโพสของ J =
 [[21 13]
 [56 39]]

ทรานสโพสของ K =
 [[14 17]
 [28 52]]

ทรานสโพส J * ทรานสโพส K =
 [[ 658 1033]
 [1876 2980]]


In [ ]:
#เฉลยแบบฝึกหัดที่ 5.1.5
M = np.array([[6, 3], [4, 5]])
N = np.array([[7, 2], [1, 9]])

# ตรวจสอบอินเวอร์ส
if np.linalg.det(M) != 0:
    M_inv = np.linalg.inv(M)
    MN = np.dot(M_inv, N)
    print("M^-1 × N =\n", MN)
else:
    print("M ไม่มีอินเวอร์ส")


M^-1 × N =
 [[ 1.77777778 -0.94444444]
 [-1.22222222  2.55555556]]


In [ ]:
#เฉลยแบบฝึกหัดที่ 5.2.1
A = sp.Matrix([[72, 19],
                     [44, 85]])
print("det(A) =", A.det())

det(A) = 5284


In [ ]:
#เฉลยแบบฝึกหัดที่ 5.2.2
B = sp.Matrix([[95, 38],
                     [64, 27]])
print("det(B) =", B.det())

det(B) = 133


In [ ]:
#เฉลยแบบฝึกหัดที่ 5.2.3
C = sp.Matrix([[45, 78, 92],
                     [63, 12, 88],
                     [90, 34, 56]])
print("det(C) =", C.det())

det(C) = 335880


In [ ]:
#เฉลยแบบฝึกหัดที่ 5.2.4
D = sp.Matrix([[89, 23, 47],
                     [56, 71, 64],
                     [12, 85, 33]])
print("det(D) =", D.det())

det(D) = -116797


In [ ]:
#เฉลยแบบฝึกหัดที่ 5.2.5
E = sp.Matrix([[67, 94, 58],
                     [42, 81, 29],
                     [75, 36, 18]])
print("det(E) =", E.det())

det(E) = -103530


In [ ]:
#เฉลยแบบฝึกหัดที่ 5.3.1
A = sp.Matrix([[4, 7, 2],
               [5, 9, 6],
               [3, 8, 1]])

# ฟังก์ชันหาไมเนอร์ M_ij
def minor(A, i, j):
    return A.minor(i, j)   # i, j นับจาก 0 (index เริ่มที่ 0)
# ฟังก์ชันหาโคแฟกเตอร์
def cofactor(A, i, j):
    return (-1)**(i + j) * minor(A, i, j)

# หาไมเนอร์ที่โจทย์กำหนด
M11 = minor(A, 0, 0)
M12 = minor(A, 0, 1)
M23 = minor(A, 1, 2)

# โคแฟกเตอร์ที่ต้องการ
C11 = cofactor(A, 0, 0)
C12 = cofactor(A, 0, 1)
C23 = cofactor(A, 1, 2)

print("M11 =", M11)
print("M12 =", M12)
print("M23 =", M23)

print("\nC11 =", C11)
print("C12 =", C12)
print("C23 =", C23)

M11 = -39
M12 = -13
M23 = 11

C11 = -39
C12 = 13
C23 = -11


In [ ]:
#เฉลยแบบฝึกหัดที่ 5.3.2
A = sp.Matrix([[10, 12, 15],
               [20, 25, 30],
               [35, 40, 45]])

# หาไมเนอร์ที่โจทย์กำหนด
M21 = minor(A, 1, 0)
M22 = minor(A, 1, 1)
M13 = minor(A, 0, 2)

# โคแฟกเตอร์ที่ต้องการ
C21 = cofactor(A, 1, 0)
C22 = cofactor(A, 1, 1)
C13 = cofactor(A, 0, 2)

print("M21 =", M21)
print("M22 =", M22)
print("M13 =", M13)

print("\nC21 =", C21)
print("C22 =", C22)
print("C13 =", C13)

M21 = -60
M22 = -75
M13 = -75

C21 = 60
C22 = -75
C13 = -75


In [ ]:
#เฉลยแบบฝึกหัดที่ 5.3.3
A = sp.Matrix([[18, 22, 30],
               [12, 28, 36],
               [40, 50, 60]])

# หาไมเนอร์ที่โจทย์กำหนด
M31 = minor(A, 2, 0)
M32 = minor(A, 2, 1)
M12 = minor(A, 0, 1)

# โคแฟกเตอร์ที่ต้องการ
C31 = cofactor(A, 2, 0)
C32 = cofactor(A, 2, 1)
C12 = cofactor(A, 0, 1)

print("M31 =", M31)
print("M32 =", M32)
print("M12 =", M12)

print("\nC31 =", C31)
print("C32 =", C32)
print("C12 =", C12)

M31 = -48
M32 = 288
M12 = -720

C31 = -48
C32 = -288
C12 = 720


In [ ]:
#เฉลยแบบฝึกหัดที่ 5.4.1
A = np.array([[2, -1, 1],
              [1, 3, 2],
              [3, 2, -2]])

b = np.array([2, 3, 10])

X = np.linalg.solve(A, b)
print(X)

[ 2.  1. -1.]


In [ ]:
#เฉลยแบบฝึกหัดที่ 5.4.2
A = np.array([[4, 1, 2],
              [0, 3, 1],
              [2, 5, 2]])

b = np.array([12, 9, 18])

X = np.linalg.solve(A, b)
print(X)

[1. 2. 3.]


In [ ]:
#เฉลยแบบฝึกหัดที่ 5.4.3
A = np.array([[3, 1, 2],
              [1, 4, -1],
              [2, 0, 5]])

b = np.array([13, -6, 24])

X = np.linalg.solve(A, b)
print(X)

[ 2. -1.  4.]


In [ ]:
#เฉลยแบบฝึกหัดที่ 5.4.4
A = np.array([[2, 3, 1],
              [1, -2, 4],
              [5, 1, 3]])

b = np.array([11, 9, 16])

X = np.linalg.solve(A, b)
print(X)

[1. 2. 3.]


In [ ]:
#เฉลยแบบฝึกหัดที่ 5.4.5
A = np.array([[2, 1, 0],
              [1, 3, 1],
              [4, -1, 2]])

b = np.array([8, 10, 12])

X = np.linalg.solve(A, b)
print(X)

[3. 2. 1.]
