In [ ]:
import numpy as np
from IPython.display import display as dp
#, Latex as lt

import sympy as sp
#sp.init_printing(use_latex=True)

In [ ]:
import numpy as np
from numpy import *

In [ ]:
#ตัวอย่างที่ 5.1
A = np.array([[2, 4, 6] , [1, 3, 5]])

B = np.array([[7, 8, 9] , [1, 2, 3]])

result = A+B

print("ผลลัพธ์ของ A+B =")
print(result)

ผลลัพธ์ของ A+B =
[[ 9 12 15]
 [ 2  5  8]]


In [ ]:
#ตัวอย่างที่ 5.2
A = np.array([[9, 5, 7] , [3, 5, 6]])

B = np.array([[5, 2, 7] , [4, 1, 4]])

result = A - B

print("ผลลัพธ์ของ A - B =")
print(result)

ผลลัพธ์ของ A - B =
[[ 4  3  0]
 [-1  4  2]]


In [ ]:
#ตัวอย่างที่ 5.3

# กำหนดเมทริกซ์ A
A = np.array([[1, 5],
              [4, 2],
              [3, 9]])

# คูณเมทริกซ์ A ด้วย 2
result = 2 * A

# แสดงผลลัพธ์
print("ผลลัพธ์ของ 2A =")
print(result)

ผลลัพธ์ของ 2A =
[[ 2 10]
 [ 8  4]
 [ 6 18]]


In [ ]:
#ตัวอย่างที่ 5.4
A = np.array([[1, 2],
                    [4, 3]])

B = np.array([[7, 8, 9],
                    [3, 2, 1]])

# คำนวณผลคูณเมทริกซ์ A x B
AB = np.dot(A, B)

# แสดงผลลัพธ์
print("ผลลัพธ์ของ A x B =")
print(AB)


ผลลัพธ์ของ A x B =
[[13 12 11]
 [37 38 39]]


In [ ]:
#ตัวอย่างที่  5.5
A = np.array([[2, -3], [5, 7], [4, 1]])
A_T = A.T
print("ทรานสโพสของเมทริกซ์ คือ")
print(A_T)


ทรานสโพสของเมทริกซ์ คือ
[[ 2  5  4]
 [-3  7  1]]


In [ ]:
#ตัวอย่างที่ 5.6
B = np.array([[1, 4, 7], [2, 5, 8], [3, 6, 9]])
B_T = B.T
print("ทรานสโพสของเมทริกซ์ คือ")
print(B_T)


ทรานสโพสของเมทริกซ์ คือ
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#ตัวอย่างที่ 5.7

A = np.array([[5, 6], [2, 3]])

det_A = np.linalg.det(A)

# ตรวจสอบว่า A มีอินเวอร์สหรือไม่
if det_A != 0:
    # ถ้า determinant ไม่เป็นศูนย์, หาอินเวอร์ส
    A_inv = np.linalg.inv(A)
    print("อินเวอร์สของเมทริกซ์ A คือ:")
    print(A_inv)
else:
    # ถ้า determinant เป็นศูนย์, ไม่มีอินเวอร์ส
    print("เมทริกซ์นี้ไม่มีอินเวอร์ส (det = 0)")


อินเวอร์สของเมทริกซ์ A คือ:
[[ 1.         -2.        ]
 [-0.66666667  1.66666667]]


In [ ]:
#ตัวอย่างที่ 5.8

B = np.array([[12, 7], [5, 10]])

det_B = np.linalg.det(B)

# ตรวจสอบว่า A มีอินเวอร์สหรือไม่
if det_B != 0:
    # ถ้า determinant ไม่เป็นศูนย์, หาอินเวอร์ส
    B_inv = np.linalg.inv(B)
    print("อินเวอร์สของเมทริกซ์ B คือ:")
    print(B_inv)
else:
    # ถ้า determinant เป็นศูนย์, ไม่มีอินเวอร์ส
    print("เมทริกซ์นี้ไม่มีอินเวอร์ส (det = 0)")

อินเวอร์สของเมทริกซ์ B คือ:
[[ 0.11764706 -0.08235294]
 [-0.05882353  0.14117647]]


In [ ]:
#ตัวอย่างโจทย์ที่ 1

# กำหนดเมทริกซ์ A และ B
A = np.array([[4, 8, 1],
              [1, 2, 0],
              [3, 5, 7]])

B = np.array([[1, 0, 4],
              [8, 3, 2],
              [6, 5, 1]])

# คำนวณ A + B, A - B, และ A * B
sum_AB = A + B  # บวกเมทริกซ์
diff_AB = A - B  # ลบเมทริกซ์
product_AB = np.dot(A, B)  # คูณเมทริกซ์

# แสดงผลลัพธ์
print("ผลลัพธ์ของ A + B:")
print(sum_AB)

print("\nผลลัพธ์ของ A - B:")
print(diff_AB)

print("\nผลลัพธ์ของ A * B:")
print(product_AB)


ผลลัพธ์ของ A + B:
[[ 5  8  5]
 [ 9  5  2]
 [ 9 10  8]]

ผลลัพธ์ของ A - B:
[[ 3  8 -3]
 [-7 -1 -2]
 [-3  0  6]]

ผลลัพธ์ของ A * B:
[[74 29 33]
 [17  6  8]
 [85 50 29]]


In [ ]:
#ตัวอย่างโจทย์ 2

# กำหนดตัวแปร theta
theta = sp.symbols('theta')

# กำหนดเมทริกซ์ A และ B
A = sp.Matrix([
    [sp.sin(theta), sp.cos(theta)],
    [-sp.cos(theta), sp.sin(theta)]
])

B = sp.Matrix([
    [sp.tan(theta), sp.sec(theta)],
    [sp.csc(theta), sp.cot(theta)]
])

# คำนวณผลลัพธ์
C = A + B
D = A - B
E = A * B

# แสดงผลลัพธ์
print("A + B =\n")
dp(C)
print("\n\nA - B =\n")
dp(D)
print("\n\nA * B =\n")
dp(E)

A + B =



Matrix([
[ sin(theta) + tan(theta), cos(theta) + sec(theta)],
[-cos(theta) + csc(theta), sin(theta) + cot(theta)]])



A - B =



Matrix([
[ sin(theta) - tan(theta), cos(theta) - sec(theta)],
[-cos(theta) - csc(theta), sin(theta) - cot(theta)]])



A * B =



Matrix([
[sin(theta)*tan(theta) + cos(theta)*csc(theta), sin(theta)*sec(theta) + cos(theta)*cot(theta)],
[sin(theta)*csc(theta) - cos(theta)*tan(theta), sin(theta)*cot(theta) - cos(theta)*sec(theta)]])

In [ ]:
#ตัวอย่างที่ 5.9
A = sp.Matrix([[3, 6],
                     [4, 2]])
print("det(A) =", A.det())

det(A) = -18


In [ ]:
#ตัวอย่างที่ 5.10
A = sp.Matrix([[0, 3, 5],
               [2, 4, 6],
               [3, 2, 0]])
print("det(A) =", A.det())

det(A) = 14


In [ ]:
#ตัวอย่างที่ 5.11
A = sp.Matrix([[2, 1, 4],
               [3, 5, 7],
               [6, 8, 9]])

# ฟังก์ชันหาไมเนอร์ M_ij
def minor(A, i, j):
    return A.minor(i, j)   # i, j นับจาก 0 (index เริ่มที่ 0)

# หาไมเนอร์ที่โจทย์กำหนด
M11 = minor(A, 0, 0)   # a11
M12 = minor(A, 0, 1)   # a12
M23 = minor(A, 1, 2)   # a23

print("M11 =", M11)
print("M12 =", M12)
print("M23 =", M23)

M11 = -11
M12 = -15
M23 = 10


In [ ]:
#ตัวอย่างที่ 5.12

# ฟังก์ชันหาโคแฟกเตอร์
def cofactor(A, i, j):
    return (-1)**(i + j) * minor(A, i, j)

# โคแฟกเตอร์ที่ต้องการ
C11 = cofactor(A, 0, 0)
C12 = cofactor(A, 0, 1)
C23 = cofactor(A, 1, 2)

print("C11 =", C11)
print("C12 =", C12)
print("C23 =", C23)


C11 = -11
C12 = 15
C23 = -10


In [ ]:
#ตัวอย่างที่ 5.13
A = sp.Matrix([[2, 1, 4],
               [3, 5, 7],
               [6, 8, 9]])

# ขยาย determinant ตามแถวแรก
det_A = sum(A[0, j] * (-1)**(0+j) * A.minor(0, j) for j in range(A.cols))

print("det(A) =", det_A)


det(A) = -31


In [ ]:
#ตัวอย่างที่ 5.14

A = np.array([[1, 2, 3],
              [2, 1, 1],
              [3, 2, 1]])

b = np.array([14, 10, 14])

X = np.linalg.solve(A, b)
print(X)

[3. 1. 3.]
